README.md, package.json, scripts/events/index.mjs
=> format output

.env.example, README.md, hardhat.config.ts, package-lock.json, package.json, scripts/mint.mjs, webapp/src/lib/contracts.ts, webapp/src/wagmi.ts
closes https://github.com/orpheuslummis/AstaVerde/issues/19
=> feat: Deployment on Base testnet

contracts/AstaVerde.sol, test/AstaVerde.behavior.ts, webapp/src/components/BatchCard.tsx, webapp/src/components/BatchListing.tsx, webapp/src/lib/contracts.ts, webapp/src/wagmi.ts
closes https://github.com/orpheuslummis/AstaVerde/issues/36
also update a few `console.log` to include 'positional data'
=> fix: display BatchID correctly, updates contract

contracts/AstaVerde.sol, webapp/src/lib/contracts.ts
unblocks https://github.com/orpheuslummis/AstaVerde/pull/40
closes https://github.com/orpheuslummis/AstaVerde/issues/46
=> fix: Sign of setAuctionTimeThresholds requirement

scripts/mint.mjs
closes https://github.com/orpheuslummis/AstaVerde/issues/42
=> feat: Futher validation on minting task

test/AstaVerde.behavior.ts
Just adding 1 test for contract
=> test: Add a test for token metadata

webapp/src/components/Header.tsx
=> fix: InvalidAddressError

webapp/src/components/Header.tsx
=> feat: active link

scripts/mint.mjs, webapp/src/app/token/[id]/page.tsx
closes https://github.com/orpheuslummis/AstaVerde/issues/54
also includes an unlisted page to display (some minimal) token information
=> fix: Correctly include CIDs in the minting

webapp/src/app/about/page.tsx, webapp/src/app/ecoassets/page.tsx
=> fix: add formatting to text in about and ecoassets

webapp/src/app/mytokens/page.tsx
redeem page show batch id
button disable on non selected items
closes #69
=> Fix: redeem page show batch id

webapp/src/components/BatchListing.tsx
=> fix: refetch first load

webapp/src/components/BatchListing.tsx
=> fix: remove batch 0

webapp/src/components/Header.tsx
=> fix: logo click back to market

webapp/src/app/mytokens/page.tsx
=> fix: redeem clickable to token id page

webapp/src/app/layout.tsx, webapp/src/app/terms/page.tsx, webapp/src/components/Footer.tsx
=> feat: add footer, add terms link, add term page

webapp/src/app/layout.tsx
=> fix: add favicon

scripts/events/contracts.mjs, webapp/src/lib/contracts.ts
This contract instance uses official testnet USDC and has batches minted properly
=> chore: Update testnet contract address

webapp/src/app/token/[id]/page.tsx
=> fix: show token image, show status

webapp/src/components/BatchCard.tsx
=> fix: 0 quantity buy button

webapp/src/components/OnboardingModal.tsx
=> fix: Can't accept intro modal on phone

webapp/src/components/BatchCard.tsx
=> fix: Image CID can be undefined

webapp/src/app/terms/page.tsx, webapp/src/app/termsofservice/page.tsx, webapp/src/components/Footer.tsx
=> fix: update Terms of service

webapp/src/app/about/page.tsx, webapp/src/components/BatchCard.tsx, webapp/src/components/OnboardingModal.tsx
=> fix: update about page content

contracts/AstaVerde.sol, test/AstaVerde.behavior.ts, test/AstaVerde.fixture.ts, test/HelperTest.ts, test/helpers.ts, webapp/src/app.config.ts, webapp/src/components/BatchCard.tsx, webapp/src/components/Header.tsx, webapp/src/lib/contracts.ts
fixes https://github.com/orpheuslummis/AstaVerde/issues/79
=> fix: USDC precision handling
